### ISSUE TITLE
Getting 0 Seeds for all event mons + not allowed to edit pokemon filter it's using it's own default filter

### ISSUE THREAD

**Issue by Ash6990** [MewTracker/sv-research#30]
![Screenshot (12585)](https://github.com/MewTracker/sv-research/assets/119098364/7d931128-11c0-4eac-8e7e-d783d805d706)

**Comment by Ash6990** [comment]
![Screenshot (12587)](https://github.com/MewTracker/sv-research/assets/119098364/40f3b89f-57f3-430c-b1ec-7245b410e64e)
crashing with certain mons too.

**Comment by MewTracker** [comment]
You are crashing because your filters are not sufficiently strict. You are getting too many results and lack memory to store them all. Keep in mind you are exploring whole seed space (00000000-FFFFFFFF), so if you are searching for something very common just reduce your search range.

Also 7* raids have almost all parameters fixed, so unless you are looking for a very specific size/weight or a rare set of rewards there's generally no point in searching for seeds.
