### ISSUE TITLE
Raid calc did not responding 

### ISSUE THREAD

**Issue by Sapikje17** [MewTracker/sv-research#32]
Tried to use raid calc to find up salty herb but it does nothing and freeze up. I did click it for specific reward filter.
![IMG_9880](https://github.com/user-attachments/assets/ad1b18ec-4bf5-4814-8af1-4bdb64ba6a46)
![IMG_9881](https://github.com/user-attachments/assets/2ed17fb7-faa5-4b09-b560-ab27c5cf929a)

**Comment by hexbyt3** [comment]
It looks like you’re trying to run this on a potato. You only have a max of 3 threads to run it on.

**Comment by Sapikje17** [comment]
> It looks like you’re trying to run this on a potato. You only have a max of 3 threads to run it on.

My bad🥲🥲..but is it a storage issue or laptop speed issue?

**Comment by hexbyt3** [comment]
It is probably both. 

It’s not ideal, but you could always use the seeds here:
https://github.com/MewTracker/sv-research/tree/master/Seeds

**Comment by Sapikje17** [comment]
Is the only solution is to use new computer or laptop then??

**Comment by Sapikje17** [comment]
one of my friends only have thread 1 but got the raid calc functioning well but don't know what's the problem with mine. @MewTracker sir, help me please.

**Comment by MewTracker** [comment]
If you are looking **only for 5 salty herbs** your filters are restrictive enough, so everything is fine (you didn't show filters, so I have to trust you here, make sure to double check). Your machine seems to be extremely old, so it will take a few minutes to find all the seeds.

If you don't need all ~3500 seeds for that search, you can reduce search space e.g. 00000000-7FFFFFFF (instead of default 00000000-FFFFFFFF). It will give you half of the results but it will also take 50% less time.

Btw print screen key exists Shift + Win + S also exists. Consider that when taking screenshots.
