### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by nlqhs** [MewTracker/sv-research#7]
Hi,
Thank you for the work. 
I was wondering if size filter would be a possible feature in raid viewer/calculator?

**Comment by MewTracker** [comment]
It's possible of course but every extra filter has impact on performance (although we have specialized code paths chosen dynamically based on user's choices to minimize this negative effect). That's why I only add things that seem to be useful. Why do you want to filter for size?

**Comment by nlqhs** [comment]
Ah I was wondering if it's possible to add for future update since size is the new thing sv brings to the game. 
I think that size filter might be more beneficial/relevant than tera type/nature/ability filters because those are changeable whereas size is fixed :)

> every extra filter has impact on performance
Would it take longer to run or would it yield more errors?

**Comment by MewTracker** [comment]
> Would it take longer to run or would it yield more errors?

Every check takes a bit of extra time and for RaidCalc performance is an absolute priority. That's what separates it from similar but PKHeX-based projects like TeraFinder. They can include some great quality of life improvements like save viewing, raid editing, etc. easily thanks to PKHeX core but can never achieve performance levels comparable to RaidCalc which is written in pure C++ with heavily-optimized code. That's how both projects complement each other.

I can't add specialized paths for every filter because growth is exponential. That's why some advanced filters like nature/ability/tera type are grouped together already. I think I can add size to this advanced group without much harm. It's the very last step of Pokémon generation anyway, so impact should be minimal (and completely non-existent for people that are not filtering for size).

I will look into this in future versions.

**Comment by nlqhs** [comment]
Thank you so much.
